"""Extract exact fixture names and fallbacks. Run from the repository root."""
import json
from pathlib import Path

directory = Path(__file__).parent
fixture = json.loads((directory / "service-data-standard.json").read_text())
entries = {}


def collect(entry):
    name, fallback = entry["shortName"], entry["fallback"]
    assert name not in entries, name
    entries[name] = fallback
    for variation in entry.get("skinVariations", []):
        collect(variation)


for entry in fixture["emojis"]:
    collect(entry)

lines = [
    "// Generated by emoji-fixture/generate.py from the pinned Atlassian fixture.",
    "// Copyright 2019 Atlassian Pty Ltd. Apache-2.0. See emoji-fixture/LICENSE.",
    "pub const entries = .{",
]
for name, fallback in sorted(entries.items()):
    lines.append(f"    .{{ {json.dumps(name)}, {json.dumps(fallback, ensure_ascii=False)} }},")
lines.append("};")
(directory.parent / "emoji_data.zig").write_text("\n".join(lines) + "\n")
