#!/usr/bin/env python3
"""Generate the Unicode data used by M21 search."""

from __future__ import annotations

import hashlib
import pathlib
import sys


def checksum(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_folds(path: pathlib.Path) -> list[tuple[int, int]]:
    folds: list[tuple[int, int]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        data = raw.split("#", 1)[0].strip()
        if not data:
            continue
        source, status, mapping = (part.strip() for part in data.split(";")[:3])
        targets = mapping.split()
        if status in {"C", "S"} and len(targets) == 1:
            folds.append((int(source, 16), int(targets[0], 16)))
    return folds


def parse_property(path: pathlib.Path, selected: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        data = raw.split("#", 1)[0].strip()
        if not data:
            continue
        codepoints, prop = (part.strip() for part in data.split(";")[:2])
        if prop != selected:
            continue
        if ".." in codepoints:
            first, last = codepoints.split("..")
        else:
            first = last = codepoints
        ranges.append((int(first, 16), int(last, 16)))
    return ranges


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: generate_search_unicode.py CaseFolding.txt DerivedCoreProperties.txt output.zig")
    case_path, properties_path, output_path = map(pathlib.Path, sys.argv[1:])
    folds = parse_folds(case_path)
    uppercase = parse_property(properties_path, "Uppercase")
    lowercase = parse_property(properties_path, "Lowercase")
    lines = [
        "//! Generated by tools/generate_search_unicode.py. Do not edit.",
        "//! Unicode version: 17.0.0.",
        f"//! CaseFolding.txt SHA-256: {checksum(case_path)}.",
        f"//! DerivedCoreProperties.txt SHA-256: {checksum(properties_path)}.",
        "",
        "pub const Fold = struct { source: u21, target: u21 };",
        "pub const Range = struct { first: u21, last: u21 };",
        "",
        "pub const folds = [_]Fold{",
    ]
    lines.extend(f"    .{{ .source = 0x{source:X}, .target = 0x{target:X} }}," for source, target in folds)
    lines.extend(["};", "", "pub const uppercase = [_]Range{"])
    lines.extend(f"    .{{ .first = 0x{first:X}, .last = 0x{last:X} }}," for first, last in uppercase)
    lines.extend(["};", "", "pub const lowercase = [_]Range{"])
    lines.extend(f"    .{{ .first = 0x{first:X}, .last = 0x{last:X} }}," for first, last in lowercase)
    lines.extend(["};", ""])
    output_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
